### ISSUE TITLE
Comment Alignment

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata#36]
### Background

In the [single post template](https://github.com/thoughtis/cata/blob/master/single.php) the [comments](https://github.com/thoughtis/cata/blob/master/comments.php) come after the [post content](https://github.com/thoughtis/cata/blob/master/template-parts/content/content.php)

The [entry component](https://github.com/thoughtis/cata/blob/master/assets/src/less/components/entry/layout.less) is synonymous with "post content" and it dictates the layout.

The comments aren't part of the post content and their layout is sort of undefined. See [the bottom of this post on Shop Catalog](https://shopcatalog.com/cute-face-masks-the-best-fashionable-face-masks-for-staying-safe/) for an example.

### Details

- [x] Update comments template to add `.comments__header` around `.comments__title` and `.comments__content` around the actual comments and the form.
- [x] Add a comments LESS component layout file that replicates the alignment of `.entry` and `.entry__content`
- [x] Create a beta release
- [x] Incorporate that beta into Shop Catalog locally so we can test it against the layout of Product Reviews which are technically comments and may share some class names.

**Comment by richdacuban** [comment]
@douglas-johnson I have successfully pulled the Cata theme into SC as you showed me. I don't think there's overlap between the classes added to cata (`.comments` and `.comments__content`) since `themes/shopcatalog/woocommerce/single-product-reviews.php` uses `#comments` not class and doesn't use `comments__content` at all. 

Is that what is intended to be checked? That the changes to the parent don't affect the previous changes I made to the SC review layouts and alignment?

- `comments.php`:
![Screen Shot 2020-06-17 at 1 49 59 PM](https://user-images.githubusercontent.com/40250614/84932609-8de4e400-b0a2-11ea-98bc-5f5385d5ad7f.png)
- `single-product-reviews.php`:
![Screen Shot 2020-06-17 at 1 47 08 PM](https://user-images.githubusercontent.com/40250614/84932612-8e7d7a80-b0a2-11ea-81f7-f2c74ec4531e.png)

?

**Comment by douglas-johnson** [comment]
@richdacuban 

> Is that what is intended to be checked? That the changes to the parent don't affect the previous changes I made to the SC review layouts and alignment?

Yes. That's all we need.

If we ever turn on comments for Shop Catalog blog posts we might need to differentiate how `.commentlist` looks for products and posts. But that's not part of this issue.

**Comment by richdacuban** [comment]
@douglas-johnson Ok great, I'll do a regular PR against master in the Cata repo then?

**Comment by douglas-johnson** [comment]
Yes
